config/routes.rb
StausMe::Application.routes.draw do
  get "requests/get_requests"

  post '/sms', to: 'requests#request_incoming', as: :request_incoming

  root 'welcome#index'

  post '/create_request', to: 'requests#create_request', as: :create_request
  get '/get_requests', to: 'api#get_requests', as: :get_requests

end

app/models/permitted_params.rb
class PermittedParams < Struct.new(:params)
  %w(request).each do |m|
    define_method(m) { params.require(m.to_sym).permit(*send("#{m}_attributes".to_sym)) }
  end

  def video_attributes
    [:telephone, :y_coords, :x_coords, :postcode, :status]
  end


end

app/models/request.rb
class Request < ActiveRecord::Base
  # Capture the pattern
  POSTCODE_REGEX = "^(GIR ?0AA|[A-PR-UWYZ]([0-9]{1,2}|([A-HK-Y][0-9]([0-9ABEHMNPRV-Y])?)|[0-9][A-HJKPS-UW]) ?[0-9][ABD-HJLNP-UW-Z]{2})$"

  require 'twilio-ruby'

  # Instance method to capture the incoming SMS
  def store_sms (body, from)
    # If the body isn't empty
    if body.strip != ''
      message = ''

      # Work out if it is a postcode
      # If its length is 1, it's a status update
      if body.length == 1
        # If they are sending a status update, we should have their mobile number - get it
        req = self.class.find_by(telephone: from)

        # We should have an object, if not then we don't hold a record for this person...
        unless req.nil?
          # Check it's a valid number
          upd = Integer(body) rescue nil

          # Update the record record
          if upd.nil?
            # Set the message
            message = 'We have not been able to set your status, we were unable to read your status - please try again?'
          else
            #req.store_status(body.to_i)  # commented out as the type is TEXT

            # Write to the database
            req.store_status(body)

            # And set the return message
            message = 'We have updated your status successfully'
          end
        else
          # Set the message
          message = 'We have not been able to set your status as we do not hold your postcode'
        end
      elsif self.class.valid_postcode?(body)
        # Store the postcode
        self.postcode = body

        # Store the incomming number
        self.telephone = from

        # Call the Geo-location
        cord = self.reverse_geolocation(body)

        # Store the Geo
        self.store_coords(cord[:lat],cord[:lon])

        #  build the return message
        message = 'We have located you, please send us a status update'
      else
        message ='We are not able to read your message - please check and try again?'
      end

      # Set up the return message from Twilio
      twiml = Twilio::TwiML::Response.new {|r| r.Message message}

      #return the for rendering
      twiml.text
    end
  end

  # Do a geo-location reverse look-up on PostCode
  def reverse_geolocation(postcode)
    # API URL for google geo
    api_url = "https://maps.googleapis.com/maps/api/geocode/json?address=#{URI.encode(postcode)}&key=AIzaSyDFNZW_WcnVprGhOTWBDIPYsqCvLB9KHoE&sensor=false"

    # Grab the response
    res = HTTParty.get(api_url)

    # Grab the lat and long from the JSON response
    lat = res["results"][0]["geometry"]["location"]["lat"]
    lon = res["results"][0]["geometry"]["location"]["lng"]

    # Return the results to the calling method
    {lat: lat,lon: lon}
  end

  # Instance method which saves the lat and long co-ordinates
  def store_coords(x_coords, y_coords)
    self.latitude = x_coords
    self.longitude = y_coords
    self.save
  end

  # Instance method which stores the status from an incomming request
  def store_status(status)
    self.status = status
    self.save
  end

  # Class method to validate the postcode passed in the body of the message
  def self.valid_postcode?(code)
    # Now load it for comparison
    pattern = Regexp.new(POSTCODE_REGEX).freeze

    # If its a match, then the postcode is valid, otherwise not
    (code.upcase =~ pattern).nil? ? false:true
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def get_requests
    # ugly controller :(
    if params[:distance].present?
      distance = params[:distance]
    else
      distance = 5
    end
    if params[:status].present?
      requests = Request.where(status: params[:status])
    else
      requests = Request.all
    end
    requests = requests.near([params[:latitude], params[:longitude], distance, :order => :distance, :units => :mi)
    render json: requests, status: 200, example_params: false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  require 'twilio-ruby'


  def get_requests
    requests = Request.all
    render json: requests, status: 200, example_params: false
  end

  # This method that captures the incoming SMS message
  def request_incoming
    # Grab the phone number for the message
    # And the message text
    from = params[:From]
    body = params[:Body]

    # Create a request
    r = Request.new
    text = r.store_sms(body, from)

    # Return the message back out
    render xml: text
  end


  def create_request
    request = Request.create
    if params[:post_code].present?
      coords = request.reverse_geolocation(params[:post_code])
    else
      coords = [params[:latitude], params[:longitude]]
    end
    request.update(telephone: params[:telephone])
    request.store_coords(coords[:lat],coords[:lon])
    request.store_status(params[:email][:status])
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def succeed thing
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "StatusMe" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/requests/get_requests.html.slim
h1 Requests#get_requests
p Find me in app/views/requests/get_requests.html.slim

app/views/welcome/index.html.slim
/! Main Page Content and Sidebar
.row#heading
  .large-10.columns
    =image_tag('logo.png', class: 'logo-image left')
    a.button.secondary.right href="http://mystate.herokuapp.com/users/sign_in" Live stats sign-in
.row#main-content
  /! Contact Details
  .large-10.columns
    h3.tagline
      | Update how you've been affected by the flooding
    p.introduction
      | Enter your phone number, and your current status below. Use the status selection to indicate whether you are urgently in need of help, or if you are ok and available to help others in need around you.
    p.introduction
      | Once you have entered your phone number, you'll be able to easily update your status, and get updates from others by SMS.
      = succeed "." do
        em all day
    .section-container.tabs data-section=""
      section.section
        h5.title
          a href="#panel1"
        .content data-slug="panel1"
          = form_tag create_request_url do
            .row.collapse#phone-row
              .large-2.columns
                label.inline.form-label Your Phone Number
              .large-10.columns
                = text_field_tag :telephone, nil, id: "yourPhone", placeholder: "+44 7xxx xxx xxx"
                = hidden_field_tag :latitude, nil, class: "latitude"
                = hidden_field_tag :longitude, nil, class: "longitude"

            .row.collapse#postcode-row
              .large-2.columns
                label.inline.form-label Your Postcode
              .large-10.columns
                = text_field_tag :post_code, nil, id: "yourPostcode", placeholder: "FL0 0DD"

            .row.collapse
              .large-2.columns
                label.inline.form-label Your Status
              .large-10.columns
                = select(:email, :status, options_for_select([["Urgent help required", "1"], ["Worried", "2"], ["Available to volunteer", "3"]]))
            .row.collapse
              .large-12.columns
                button.radius.button type="submit"
                  | Update my status

            //input.latitude type='hidden'
            //input.longitude type='hidden'
  /! End Contact Details
  /! Sidebar
  / .large-3.columns
  /   h5 Map
  /   /! Clicking this placeholder fires the mapModal Reveal modal
  /   p
  /     a data-reveal-id="mapModal" href=""
  /       / img src="http://placehold.it/400x280"
  /     br/
  /     a data-reveal-id="mapModal" href=""
  /   p
  /     | a
  /     br/
  /     | b
  /! End Sidebar
/! End Main Content and Sidebar
/! Footer
footer.row
  .large-12.columns
    hr/
    .row
      .large-6.columns
        | Created at
        a target="_blank" href="https://twitter.com/search?q=%23floodhack"  #FloodHack
        |, in
        a target="_blank" href="http://www.campuslondon.com/‎"  Google Campus
        |  2014
      .large-6.columns
        ul.inline-list.right
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
/! End Footer
/! Map Modal
#mapModal.reveal-modal
  h4 Where We Are
  p
    / img src="http://placehold.it/800x600"
  /! Any anchor with this class will close the modal. This also inherits certain styles, which can be overriden.
  a.close-reveal-modal href="#"